export enum Roles {
	USER = 'ROLE_USER',
	ADMIN = 'ROLE_ADMIN',
	SAVE = 'ROLE_SAVE',
	UPDATE = 'ROLE_UPDATE',
	DELETE = 'ROLE_DELETE',
	VIEW = 'ROLE_UPDATE',
	GROUP_SAVE = 'ROLE_GROUP_SAVE',
	GROUP_UPDATE = 'ROLE_GROUP_UPDATE',
	GROUP_VIEW = 'ROLE_GROUP_VIEW',
	GROUP_DELETE = 'ROLE_GROUP_DELETE',
	USER_SAVE = 'ROLE_USER_SAVE',
	USER_UPDATE = 'ROLE_USER_UPDATE',
	USER_VIEW = 'ROLE_USER_VIEW',
	USER_DELETE = 'ROLE_USER_DELETE',

}
